### ISSUE TITLE
Manual Setup

### ISSUE THREAD

**Issue by wtaylor-npute** [tid-kijyun/Kanna#50]
I am trying to do a manual import to my xcode project as in step 4 the process below:

In the project settings add $(SDKROOT)/usr/include/libxml2 to the "header search paths" field

I keep getting a build error that says "No such module 'libxml2'

I am using xcode 7.2 running on El Capitan.

Any help you can provide would be greatly appreciated.

Thanks in advance.

**Comment by tid-kijyun** [comment]
Hi @wtaylor-npute 

I've updated the README.md.
Could you please do steps 1 through 3.

note of step2: The folder COPY to your project folder.

Thanks

**Comment by wtaylor-npute** [comment]
I am still having issues.  I setup a brand new IOS project.  I used the pod file method.  It imported version 1.0.3.  It can't find 1.0.4.  I get this error when I try use any Kanna code in my unit tests.  Error:(15, 10) 'libxml/xmlversion.h' file not found

I am using xcode 7.2

**Comment by tid-kijyun** [comment]
Hi @wtaylor-npute 

I've updated the podspec.
Please try `pod install` once again.

**Comment by wtaylor-npute** [comment]
Ok I was able to pull down 1.0.4 now.  I think I worked out all my issues.  Thanks!
